name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-west-2"           
  S3_BUCKET: "pasansa-poc-dataset"            
  S3_PATH: "simple-workflow/run-01"                

permissions:
  contents: read

jobs:
  AutoSync:
    name: AutoSync
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to S3
      run: |
        aws s3 sync . s3://${{ env.S3_BUCKET }}/${{ env.S3_PATH }} --delete

  dev:
    needs: AutoSync
    name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Development environment"

  staging:
    needs: dev
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment"

  integ-test:
    needs: staging
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests
        run: echo "Performing Integration Tests"

  prod:
    needs: integ-test
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production environment"
